#!/bin/bash
### Functions
grow_mmcblk(){
bash growpart /dev/mmcblk0 2 > /dev/null 2>&1
sleep 1s
resize2fs /dev/mmcblk0p2 > /dev/null 2>&1
}

grow_mmcblk1(){
bash growpart /dev/mmcblk1 2 > /dev/null 2>&1
sleep 1s
resize2fs /dev/mmcblk1p2 > /dev/null 2>&1
}

chk_mmcblk(){
fsck.fat -trawl /dev/mmcblk0p1 > /dev/null 2>&1
}

chk_mmcblk1(){
fsck.fat -trawl /dev/mmcblk1p1 > /dev/null 2>&1
}

### Grow Partition
if ls /dev/mmcblk0 2>/dev/null; then grow_mmcblk;
        else : &>/dev/null;
fi

if ls /dev/mmcblk1 2>/dev/null; then grow_mmcblk1;
        else : &>/dev/null;
fi

### Renew SSH keys
sleep 1s
/bin/rm -v /etc/ssh/ssh_host_* > /dev/null 2>&1
dpkg-reconfigure openssh-server > /dev/null 2>&1
systemctl restart ssh > /dev/null 2>&1
### Fix boot partition
umount /boot
sleep 1s
if ls /dev/mmcblk0 1>/dev/null; then chk_mmcblk;
        else : &>/dev/null;
fi

if ls /dev/mmcblk1 1>/dev/null; then chk_mmcblk1;
        else : &>/dev/null;
fi

sleep 1s
mount /boot

### Clean up
systemctl disable firstboot > /dev/null 2>&1
update-rc.d firstboot remove > /dev/null 2>&1
chown root:messagebus /usr/lib/dbus-1.0/dbus-daemon-launch-helper
chmod u+s /usr/lib/dbus-1.0/dbus-daemon-launch-helper
rm -f /etc/opt/part-uuid.txt
rm -f /var/cache/debconf/*
rm -f /usr/local/sbin/firstboot
