#!/bin/bash
source /boot/username.txt
source /etc/opt/soc.txt

bcm2711_user () {
adduser ${user} --gecos ${user^} --disabled-password
echo "${user}:${passwd}" | chpasswd
adduser ${user} sudo
adduser ${user} audio
adduser ${user} dialout
adduser ${user} video
adduser ${user} disk
adduser ${user} spi
adduser ${user} i2c
adduser ${user} gpio
adduser ${user} plugdev
adduser ${user} netdev
adduser ${user} bluetooth
adduser ${user} input
adduser ${user} tty
adduser ${user} lightdm
usermod -a -G render ${user}
}

xfce4_configs () {
unzip -qq /etc/opt/xfce-config.zip -d /etc/opt/
rm -f /etc/opt/xfce-config.zip
tar xf /etc/opt/xfce-config/config.tar.xz -C /etc/opt/xfce-config/
mv -f /etc/opt/xfce-config/config/* /home/${user}/.config/
mkdir -p /home/${user}/.icons
tar xf /etc/opt/xfce-config/Flat-Remix-Blue.tar.xz -C /etc/opt/xfce-config/
mv -f /etc/opt/xfce-config/Flat-Remix-Blue /home/${user}/.icons/
tar xf /etc/opt/xfce-config/Flat-Remix-Blue-Dark.tar.xz -C /etc/opt/xfce-config/
mv -f /etc/opt/xfce-config/Flat-Remix-Blue-Dark /home/${user}/.icons/
mkdir -p /usr/share/backgrounds/xfce/
mv -f /etc/opt/xfce-config/debian_dark_blue.png /usr/share/backgrounds/xfce/
rm -fdr /etc/opt/xfce-config
sed -i "s/#autologin-user=/autologin-user=${user}/g" /etc/lightdm/lightdm.conf
sed -i "s/user/${user}/g" /home/${user}/.config/menus/xfce-applications.menu
chown -R ${user}:${user} /home/${user}
rm -f /etc/lightdm/lightdm-gtk-greeter.conf
tee /etc/lightdm/lightdm-gtk-greeter.conf <<EOF
[greeter]
background = /usr/share/backgrounds/xfce/debian_dark_blue.png
theme-name = Adwaita-dark
xft-antialias = true
xft-hintstyle = hintfull
xft-rgba = rgb
icon-theme-name = Suru++
font-name = Sans 10
position = 50%,center 50%,center
screensaver-timeout = 10
panel-position = bottom
indicators = ~host;~spacer;~clock;~spacer;~language;~session;~power
#default-user-image =
hide-user-image = true

EOF
}

user_skins () {
mkdir -p /home/${user}/.config/mc
mv -f /etc/opt/user-ini /home/${user}/.config/mc/ini
mv -f /etc/opt/nanorc-user /home/${user}/.nanorc
chown -R ${user}:${user} /home/${user}
}

create_sudoers () {
rm -f /etc/sudoers.d/010_pi-nopasswd
tee /etc/sudoers.d/010_${user}-nopasswd <<EOF
${user} ALL=(ALL) NOPASSWD: ALL
EOF
}

rpi_eeprom () {
mv -f /etc/opt/eeprom /home/${user}/.eeprom
chown -R ${user}:${user} /home/${user}/.eeprom
}

case `grep -Fx "bcm2711" "/etc/opt/soc.txt" >/dev/null; echo $?` in
  0)
	bcm2711_user
	create_sudoers
	rpi_eeprom
	user_skins
	xfce4_configs
    ;;
esac

rm -f /boot/username.txt
rm -f /usr/local/bin/whogoesthere
