#!/bin/bash
source lib/source
source lib/function/kernel
source lib/function/echoes
source lib/function/wireless
source userdata.txt
UD=userdata.txt

userdata () {
echo ""
echo -e "You have ${RED}not${FIN} created a ${RED}userdata.txt${FIN} file."
while [ true ] ; do
read -t 3 -n 1
if [ $? = 0 ] ; then
exit ;
else
dialog --infobox "Please review the README.md or run make config." 3 51
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo -e "${YLW}$UD file found${FIN}."
else 
    userdata
fi

case `grep -Fx "devuser=1" "userdata.txt" >/dev/null; echo $?` in
  0)
    echo ""
    echo -e "${RED}Wrong userdata file${FIN}!"
    echo ""
    while [ true ] ; do
    read -t 2 -n 1
    if [ $? = 0 ] ; then
    exit ;
    else
    dialog --infobox "Please review the README.md or run make config." 3 51
    fi
    done
    ;;
esac

# prep
source_dir
clean_source
download
extract
armv8_setup;
if `grep -Fx "crosscompile=1" "../../userdata.txt" >/dev/null;`
	then ccpatch; else ncpatch;
fi
choose_rpi4_defconfig;
choose_v8_menuconfig
choose_v8_compile
echo
cd ..
rm -f linux-libc-dev*.deb
rm -f *.buildinfo
rm -f *.changes
if `grep -Fx "uboot=0" "../userdata.txt" >/dev/null;`
	then mkdir -p ${FPI4} && mv -f *.deb ${FPI4}/
fi
if `grep -Fx "uboot=1" "../userdata.txt" >/dev/null;`
	then mkdir -p ${TPI4} && mv -f *.deb ${TPI4}/
fi
echo_done
