#!/bin/bash
#AARCH64 ROOTFS
RED="\e[0;31m"
BRED="\e[1;31m"
GRN="\e[0;32m"
YLW="\e[1;33m"
GRY="\e[0;37m"
WHT="\e[1;37m"
FIN="\e[0m"
source userdata.txt > /dev/null 2>&1;
source lib/source
UD=userdata.txt

userdata(){
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    :;
else 
    userdata
fi
echo
validation
if `grep -Fx "verbose=1" "userdata.txt" > /dev/null 2>&1;`
	then set -eux -o pipefail;
	else set -eu -o pipefail;
fi
ROOT="sysroot"
ROOTFS_ARCH="rootfs-aarch64"
RELEASE=${DISTRO}-${DISTRO_VERSION}-${ROOTFS_ARCH}.tar.xz
if ls $RELEASE > /dev/null 2>&1;
	then ls $RELEASE && exit;
fi
echo -e "${GRN}Starting debootstrap${FIN} ..."
echo -e -n ${RED}

# start debootstrap
mkdir -p ${ROOT}/usr/bin
cp $(which "qemu-aarch64-static") ${ROOT}/usr/bin
debootstrap --arch arm64 --foreign ${DISTRO_VERSION} ${ROOT}
chroot ${ROOT} /debootstrap/debootstrap --second-stage
rm -f ${ROOT}/usr/bin/qemu-aarch64-static
rm -f ${ROOT}/var/cache/debconf/*

# finish
echo
echo -e "${BRED}Archiving root filesystem${FIN} ..."
cd ${ROOT}
echo -e -n ${WHT}
XZ_DEFAULTS="--threads=${CORES}"; export XZ_DEFAULTS;tar cfJ - * | (pv -terb > ../$RELEASE)
echo -e -n ${FIN}
cd ..

rm -fdr ${ROOT}
clear
