#!/bin/bash
source lib/function/echoes
source lib/function/boot
source lib/source
source userdata.txt > /dev/null 2>&1
UD=userdata.txt > /dev/null 2>&1

userdata () {
echo ""
echo "Please create a userdata.txt file"
while [ true ] ; do
read -t 10 -n 1
if [ $? = 0 ] ; then
exit ;
else
echo "run make config"
fi
done
}

if [ -f "$UD" ]; then
    echo ""
    echo "$UD file found." > /dev/null 2>&1
else 
    userdata
fi
### Boards
if `grep -Fx "bcm2711" "soc.txt" >/dev/null;`
    then bcm2711_uboot_string;
fi
